export const appwriteConfig = {
  endpointUrl: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
  projectId: process.env.NEXT_PUBLIC_APPWRITE_PROJECT!,
  databaseId: process.env.NEXT_PUBLIC_APPWRITE_DATABASE!,
  categoriesCollectionId: process.env.NEXT_PUBLIC_APPWRITE_CATEGORIES_COLLECTION!,
  sizesCollectionId: process.env.NEXT_PUBLIC_APPWRITE_SIZES_COLLECTION!,
  pizzasCollectionId: process.env.NEXT_PUBLIC_APPWRITE_PIZZAS_COLLECTION!,
  vouchersCollectionId: process.env.NEXT_PUBLIC_APPWRITE_VOUCHERS_COLLECTION!,
  cartItemsCollectionId: process.env.NEXT_PUBLIC_APPWRITE_CART_ITEMS_COLLECTION!,
  ordersCollectionId: process.env.NEXT_PUBLIC_APPWRITE_ORDERS_COLLECTION!,
  usersCollectionId: process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION!,
  toppingsCollectionId: process.env.NEXT_PUBLIC_APPWRITE_TOPPINGS_COLLECTION!,
  bucketId: process.env.NEXT_PUBLIC_APPWRITE_BUCKET!,
  secretKey: process.env.NEXT_APPWRITE_KEY!,
};